[project]
name = "fiftyone"
version = "0.1.0"
description = "A short description"
requires-python = ">=3.8"
dependencies = [
    "fiftyone>=0.25.2",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
